/**
 * YouTube Data API v3公式実装
 * 非公式youtubei.jsの代替として安全で準拠した実装
 */

import { google } from 'googleapis';
import { quotaManager, rateLimiter, YOUTUBE_API_CONFIG } from '../config/youtube-api';
import { securityLogger } from '../utils/securityLogger';

/**
 * YouTube API クライアント
 */
const youtube = google.youtube({
  version: 'v3',
  auth: process.env.YOUTUBE_API_KEY || '',
});

/**
 * 動画情報取得インターフェース
 */
export interface YouTubeVideoInfo {
  id: string;
  title: string;
  description: string;
  duration: string;
  publishedAt: string;
  channelTitle: string;
  defaultLanguage?: string;
  captionsAvailable: boolean;
}

/**
 * 字幕情報インターフェース
 */
export interface YouTubeCaptions {
  text: string;
  language: string;
  isAutoGenerated: boolean;
}

/**
 * API使用量とエラー情報
 */
export interface YouTubeAPIResponse<T> {
  data: T;
  quotaUsed: number;
  remainingQuota: number;
  success: boolean;
  error?: string;
}

/**
 * YouTube Data API v3を使用した安全な動画情報取得
 */
export class YouTubeOfficialService {
  /**
   * 動画IDから動画情報を取得
   */
  async getVideoInfo(videoId: string): Promise<YouTubeAPIResponse<YouTubeVideoInfo | null>> {
    try {
      // API制限チェック
      const quotaCost = YOUTUBE_API_CONFIG.quotas.costPerRequest.videoDetails;
      if (!quotaManager.canMakeRequest(quotaCost)) {
        return {
          data: null,
          quotaUsed: 0,
          remainingQuota: quotaManager.getRemainingQuota(),
          success: false,
          error: '1日のAPI使用量上限に達しました',
        };
      }

      // レート制限チェック
      await rateLimiter.checkRateLimit();

      // 動画情報取得
      const response = await youtube.videos.list({
        part: ['snippet', 'contentDetails', 'status'],
        id: [videoId] as string[],
      });

      // クォータ使用量を記録
      quotaManager.addUsage(quotaCost);

      const video = response.data.items?.[0];
      if (!video) {
        return {
          data: null,
          quotaUsed: quotaCost,
          remainingQuota: quotaManager.getRemainingQuota(),
          success: false,
          error: '動画が見つかりません',
        };
      }

      const videoInfo: YouTubeVideoInfo = {
        id: video.id!,
        title: video.snippet?.title || '',
        description: video.snippet?.description || '',
        duration: video.contentDetails?.duration || '',
        publishedAt: video.snippet?.publishedAt || '',
        channelTitle: video.snippet?.channelTitle || '',
        defaultLanguage: video.snippet?.defaultLanguage,
        captionsAvailable: video.contentDetails?.caption === 'true',
      };

      // 成功ログ
      securityLogger.log(
        'INFO' as const,
        'YOUTUBE_API_SUCCESS',
        'Video information retrieved successfully',
        {
          videoId,
          quotaUsed: quotaCost,
          remainingQuota: quotaManager.getRemainingQuota(),
        }
      );

      return {
        data: videoInfo,
        quotaUsed: quotaCost,
        remainingQuota: quotaManager.getRemainingQuota(),
        success: true,
      };

    } catch (error) {
      console.error('YouTube API error:', error);
      
      securityLogger.log(
        'ERROR' as const,
        'YOUTUBE_API_ERROR',
        'Failed to retrieve video information',
        {
          videoId,
          error: error instanceof Error ? error.message : 'Unknown error',
        }
      );

      return {
        data: null,
        quotaUsed: 0,
        remainingQuota: quotaManager.getRemainingQuota(),
        success: false,
        error: error instanceof Error ? error.message : 'YouTube API呼び出しに失敗しました',
      };
    }
  }

  /**
   * 動画の字幕を取得
   */
  async getCaptions(videoId: string, languageCode: string = 'ja'): Promise<YouTubeAPIResponse<YouTubeCaptions | null>> {
    try {
      // API制限チェック
      const quotaCost = YOUTUBE_API_CONFIG.quotas.costPerRequest.captions;
      if (!quotaManager.canMakeRequest(quotaCost)) {
        return {
          data: null,
          quotaUsed: 0,
          remainingQuota: quotaManager.getRemainingQuota(),
          success: false,
          error: '1日のAPI使用量上限に達しました',
        };
      }

      // レート制限チェック
      await rateLimiter.checkRateLimit();

      // 字幕リスト取得
      const captionsResponse = await youtube.captions.list({
        part: ['snippet'],
        videoId: videoId,
      });

      const captions = captionsResponse.data.items || [];
      
      // 日本語字幕を優先的に探す
      let targetCaption = captions.find(caption => 
        caption.snippet?.language === languageCode
      );

      // 日本語がない場合は英語を探す
      if (!targetCaption && languageCode === 'ja') {
        targetCaption = captions.find(caption => 
          caption.snippet?.language === 'en'
        );
      }

      // それでもない場合は最初の字幕を使用
      if (!targetCaption && captions.length > 0) {
        targetCaption = captions[0];
      }

      if (!targetCaption) {
        quotaManager.addUsage(1); // リスト取得のコスト
        return {
          data: null,
          quotaUsed: 1,
          remainingQuota: quotaManager.getRemainingQuota(),
          success: false,
          error: '字幕が利用できません',
        };
      }

      // 字幕ダウンロード
      const captionId = targetCaption.id!;
      const downloadResponse = await youtube.captions.download({
        id: captionId,
        tfmt: 'srt', // SubRip形式
      });

      // クォータ使用量を記録
      quotaManager.addUsage(quotaCost);

      const captionText = downloadResponse.data as string;
      
      // SRT形式からテキストのみを抽出
      const cleanText = this.extractTextFromSRT(captionText);

      const result: YouTubeCaptions = {
        text: cleanText,
        language: targetCaption.snippet?.language || 'unknown',
        isAutoGenerated: targetCaption.snippet?.trackKind === 'asr',
      };

      securityLogger.log(
        'INFO' as const,
        'YOUTUBE_CAPTIONS_SUCCESS',
        'Captions retrieved successfully',
        {
          videoId,
          language: result.language,
          isAutoGenerated: result.isAutoGenerated,
          textLength: cleanText.length,
          quotaUsed: quotaCost,
        }
      );

      return {
        data: result,
        quotaUsed: quotaCost,
        remainingQuota: quotaManager.getRemainingQuota(),
        success: true,
      };

    } catch (error) {
      console.error('YouTube captions error:', error);
      
      securityLogger.log(
        'ERROR' as const,
        'YOUTUBE_CAPTIONS_ERROR',
        'Failed to retrieve captions',
        {
          videoId,
          languageCode,
          error: error instanceof Error ? error.message : 'Unknown error',
        }
      );

      return {
        data: null,
        quotaUsed: 0,
        remainingQuota: quotaManager.getRemainingQuota(),
        success: false,
        error: error instanceof Error ? error.message : '字幕の取得に失敗しました',
      };
    }
  }

  /**
   * SRT形式から純粋なテキストを抽出
   */
  private extractTextFromSRT(srtContent: string): string {
    const lines = srtContent.split('\n');
    const textLines: string[] = [];
    let isTextLine = false;

    for (const line of lines) {
      const trimmedLine = line.trim();
      
      // 空行の場合は次のセクションへ
      if (trimmedLine === '') {
        isTextLine = false;
        continue;
      }
      
      // 数字のみの行（セクション番号）
      if (/^\d+$/.test(trimmedLine)) {
        isTextLine = false;
        continue;
      }
      
      // タイムスタンプ行
      if (/\d{2}:\d{2}:\d{2}[,\.]\d{3}\s*-->\s*\d{2}:\d{2}:\d{2}[,\.]\d{3}/.test(trimmedLine)) {
        isTextLine = true;
        continue;
      }
      
      // テキスト行
      if (isTextLine && trimmedLine) {
        // HTMLタグを除去
        const cleanLine = trimmedLine
          .replace(/<[^>]*>/g, '')
          .replace(/&lt;/g, '<')
          .replace(/&gt;/g, '>')
          .replace(/&amp;/g, '&')
          .trim();
        
        if (cleanLine) {
          textLines.push(cleanLine);
        }
      }
    }

    return textLines.join(' ').replace(/\s+/g, ' ').trim();
  }

  /**
   * 動画URLから動画IDを抽出
   */
  extractVideoId(url: string): string | null {
    const patterns = [
      /(?:youtube\.com\/watch\?v=)([^&\n?#]+)/,
      /(?:youtu\.be\/)([^&\n?#]+)/,
      /(?:youtube\.com\/embed\/)([^&\n?#]+)/,
      /(?:youtube\.com\/v\/)([^&\n?#]+)/
    ];
    
    for (const pattern of patterns) {
      const match = url.match(pattern);
      if (match && match[1]) {
        return match[1];
      }
    }
    
    return null;
  }

  /**
   * 完全な動画処理（動画情報取得 + 字幕取得）
   */
  async processVideo(url: string): Promise<YouTubeAPIResponse<{ videoInfo: YouTubeVideoInfo; captions: YouTubeCaptions } | null>> {
    const videoId = this.extractVideoId(url);
    if (!videoId) {
      return {
        data: null,
        quotaUsed: 0,
        remainingQuota: quotaManager.getRemainingQuota(),
        success: false,
        error: '無効なYouTube URLです',
      };
    }

    // 動画情報取得
    const videoInfoResponse = await this.getVideoInfo(videoId);
    if (!videoInfoResponse.success || !videoInfoResponse.data) {
      return {
        data: null,
        quotaUsed: videoInfoResponse.quotaUsed,
        remainingQuota: videoInfoResponse.remainingQuota,
        success: false,
        error: videoInfoResponse.error || '動画情報の取得に失敗しました',
      };
    }

    // 字幕取得
    const captionsResponse = await this.getCaptions(videoId);
    if (!captionsResponse.success || !captionsResponse.data) {
      return {
        data: null,
        quotaUsed: videoInfoResponse.quotaUsed + captionsResponse.quotaUsed,
        remainingQuota: captionsResponse.remainingQuota,
        success: false,
        error: captionsResponse.error || '字幕の取得に失敗しました',
      };
    }

    return {
      data: {
        videoInfo: videoInfoResponse.data,
        captions: captionsResponse.data,
      },
      quotaUsed: videoInfoResponse.quotaUsed + captionsResponse.quotaUsed,
      remainingQuota: captionsResponse.remainingQuota,
      success: true,
    };
  }

  /**
   * API使用状況の取得
   */
  getUsageStats() {
    return quotaManager.getUsageStats();
  }
}

/**
 * グローバルYouTubeサービスインスタンス
 */
export const youtubeService = new YouTubeOfficialService();