import { extractTextFromYouTubeWithGemini } from './gemini';
import { youtubeService } from './youtube-official';
import { securityLogger } from '../utils/securityLogger';

export async function extractYouTubeSubtitles(url: string): Promise<string> {
  try {
    console.log('Extracting YouTube content from:', url);
    
    // Extract video ID from URL
    const videoId = extractVideoId(url);
    if (!videoId) {
      throw new Error("無効なYouTube URLです");
    }

    console.log('Video ID:', videoId);

    // Try official YouTube Data API first
    try {
      console.log('Using official YouTube Data API to extract captions...');
      const result = await youtubeService.processVideo(url);
      
      if (result.success && result.data?.captions.text) {
        const captionsText = result.data.captions.text;
        console.log('Successfully extracted captions using YouTube Data API, length:', captionsText.length);
        
        securityLogger.log(
          'INFO',
          'YOUTUBE_OFFICIAL_SUCCESS',
          'YouTube captions extracted successfully via official API',
          {
            videoId,
            contentLength: captionsText.length,
            quotaUsed: result.quotaUsed,
            language: result.data.captions.language,
            isAutoGenerated: result.data.captions.isAutoGenerated
          }
        );
        
        return captionsText;
      } else {
        console.log('Official API failed or no captions available:', result.error);
        throw new Error(result.error || 'No captions available');
      }
      
    } catch (apiError) {
      console.log('Official YouTube API failed, falling back to Gemini Vision:', apiError);
      
      // Fallback to Gemini Vision approach
      try {
        console.log('Using Gemini Vision fallback to extract content from YouTube video...');
        const extractedText = await extractTextFromYouTubeWithGemini(videoId, url);
        
        if (extractedText && extractedText.length > 50) {
          console.log('Successfully extracted text using Gemini Vision fallback, length:', extractedText.length);
          
          securityLogger.log(
            'INFO',
            'YOUTUBE_GEMINI_FALLBACK',
            'YouTube content extracted via Gemini fallback',
            {
              videoId,
              contentLength: extractedText.length,
              fallbackReason: apiError instanceof Error ? apiError.message : 'API unavailable'
            }
          );
          
          return extractedText;
        } else {
          throw new Error("動画から十分なテキストコンテンツを抽出できませんでした");
        }
        
      } catch (geminiError) {
        console.log('Both official API and Gemini extraction failed:', geminiError);
        throw new Error("この動画からコンテンツを抽出できませんでした。字幕が利用可能な動画をお試しください。");
      }
    }
    
  } catch (error) {
    console.error('YouTube content extraction error:', error);
    throw new Error(`YouTube動画の処理に失敗しました: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

function extractVideoId(url: string): string | null {
  // Handle various YouTube URL formats
  const patterns = [
    /(?:youtube\.com\/watch\?v=)([^&\n?#]+)/,
    /(?:youtu\.be\/)([^&\n?#]+)/,
    /(?:youtube\.com\/embed\/)([^&\n?#]+)/,
    /(?:youtube\.com\/v\/)([^&\n?#]+)/
  ];
  
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match && match[1]) {
      console.log(`Video ID extracted: ${match[1]} from URL: ${url}`);
      return match[1];
    }
  }
  
  console.log(`No video ID found in URL: ${url}`);
  return null;
}
